import 'server-only';
import {saveEntry,saveEntries,type SaveInput,type OperationGuard,operationGuard,listEntries,hash,readSecret,writeSecret,acquireRefreshLock,releaseRefreshLock} from './store';
import {importCalendar} from './imports';
import {localDate,profileOf,ofKind,matchWorkout,type Workout,type Entry,type Plan} from './domain';
export {readSecret,writeSecret} from './store';
export const config=()=>process.env;
export const PROVIDERS=['whoop','strava','tredict','runna'] as const;
export type Provider=typeof PROVIDERS[number];
type Raw=Record<string,unknown>;
const record=(x:unknown):Raw=>x&&typeof x==='object'&&!Array.isArray(x)?x as Raw:{};
const records=(x:unknown):Raw[]=>Array.isArray(x)?x.map(record):[];
const n=(x:unknown):number|null=>typeof x==='number'&&Number.isFinite(x)?x:null;
async function sourceJson(response:Response):Promise<unknown>{try{return await response.json();}catch{throw new Error('Source returned invalid JSON. Sync or authorization is incomplete.');}}
function sourceId(value:unknown){if((typeof value!=='string'&&typeof value!=='number')||!String(value))throw new Error('Source returned a record without an ID. Sync is incomplete.');return String(value);}
export async function fetchSource(url:string,token?:string,deadline?:number){for(let attempt=0;attempt<3;attempt++){if(deadline&&Date.now()>deadline-1000)throw new Error('Sync reached its time limit. Existing records are retained; retry later.');let response:Response;try{response=await fetch(url,{headers:token?{Authorization:`Bearer ${token}`}:{},redirect:'error',cache:'no-store',signal:AbortSignal.timeout(deadline?Math.max(1,Math.min(15000,deadline-Date.now())):15000)});}catch{throw new Error('Source could not be reached. Retry later.');}if(response.ok)return response;if((response.status===429||response.status>=500)&&attempt<2){const raw=response.headers.get('retry-after'),seconds=raw?Number(raw):1;await new Promise(r=>setTimeout(r,Math.min(5000,Number.isFinite(seconds)?Math.max(1,seconds)*1000:1000)));continue;}throw new Error(response.status===401?'Authorization expired. Reconnect this source.':response.status===403?'Access denied. Check your permissions or plan.':response.status===429?'Source rate limit reached. Try again later.':`Source request failed (${response.status}). Retry later.`);}throw new Error('Source temporarily unavailable.');}
export function appOrigin(){const value=config().APP_ORIGIN;if(!value)throw new Error('Set APP_ORIGIN to your Remy address on the server.');const url=new URL(value);if(url.pathname!=='/'||url.search||url.hash||url.username||url.password||(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1'].includes(url.hostname))))throw new Error('APP_ORIGIN must be an HTTPS origin, or localhost for development.');return url.origin;}
export function validateRunnaUrl(value:string){const url=new URL(value.replace(/^webcal:/,'https:'));if(url.protocol!=='https:'||url.username||url.password||url.port||!/(^|\.)runna\.com$/i.test(url.hostname))throw new Error('Use an HTTPS feed on runna.com. If Runna provides another host, import its ICS file instead.');return url.href;}
async function credential(owner:string,provider:'tredict'|'runna'){const state=await operationGuard(owner,provider);if(state.disabled)return undefined;const saved=await readSecret<{value:string}>(owner,provider);if(saved?.value)return saved.value;const c=config();return c.SYNC_OWNER_ID===owner?(provider==='tredict'?c.TREDICT_TOKEN:c.RUNNA_FEED_URL):undefined;}
export async function configuredSources(owner:string){const c=config(),configurationErrors:Record<string,string>={};async function isolated<T>(provider:string,promise:Promise<T>){try{return await promise;}catch(error){configurationErrors[provider]=error instanceof Error?error.message:'Connection settings could not be read.';return null;}}const [tredict,runna,whoop,strava]=await Promise.all([isolated('tredict',credential(owner,'tredict')),isolated('runna',credential(owner,'runna')),isolated('whoop',readSecret(owner,'whoop')),isolated('strava',readSecret(owner,'strava'))]);return{configured:{tredict:!!tredict,runna:!!runna,whoop:!!(c.WHOOP_CLIENT_ID&&c.WHOOP_CLIENT_SECRET&&c.SECRET_ENCRYPTION_KEY&&c.APP_ORIGIN),strava:!!(c.STRAVA_CLIENT_ID&&c.STRAVA_CLIENT_SECRET&&c.SECRET_ENCRYPTION_KEY&&c.APP_ORIGIN)},authorized:{tredict:!!tredict,runna:!!runna,whoop:!!whoop,strava:!!strava},configurationErrors};}
export interface OAuthTokens{access_token:string;refresh_token:string;expiresAt:number;scope?:string}
export function tokenPayload(value:unknown,provider:'whoop'|'strava'):OAuthTokens{const raw=record(value),expiry=provider==='strava'?n(raw.expires_at):null,expiresIn=n(raw.expires_in);if(typeof raw.access_token!=='string'||typeof raw.refresh_token!=='string'||(!expiry&&!expiresIn))throw new Error('The source returned incomplete authorization data. Reconnect this source.');return{access_token:raw.access_token,refresh_token:raw.refresh_token,expiresAt:expiry?expiry*1000:Date.now()+expiresIn!*1000,...typeof raw.scope==='string'?{scope:raw.scope}:{}};}
export async function providerToken(owner:string,provider:'whoop'|'strava',capturedGuard?:OperationGuard){const guard=capturedGuard??await operationGuard(owner,provider);let token=await readSecret<OAuthTokens>(owner,provider);if(!token)throw new Error(`Connect ${provider==='whoop'?'WHOOP':'Strava'} to authorize data access.`);if(token.expiresAt>Date.now()+60000)return token.access_token;const lock=await acquireRefreshLock(owner,`${provider}:refresh`);if(!lock)throw new Error('Authorization renewal is already running. Retry in a moment.');try{token=await readSecret<OAuthTokens>(owner,provider);if(!token)throw new Error('Connection was removed. Reconnect this source.');if(token.expiresAt>Date.now()+60000)return token.access_token;const c=config(),clientId=provider==='whoop'?c.WHOOP_CLIENT_ID:c.STRAVA_CLIENT_ID,clientSecret=provider==='whoop'?c.WHOOP_CLIENT_SECRET:c.STRAVA_CLIENT_SECRET;if(!clientId||!clientSecret)throw new Error('Provider application credentials are missing from server settings.');const form=new URLSearchParams({grant_type:'refresh_token',refresh_token:token.refresh_token,client_id:clientId,client_secret:clientSecret});if(provider==='whoop')form.set('scope','offline');let response:Response;try{response=await fetch(provider==='whoop'?'https://api.prod.whoop.com/oauth/oauth2/token':'https://www.strava.com/oauth/token',{method:'POST',body:form,redirect:'error',signal:AbortSignal.timeout(15000)});}catch{throw new Error('Authorization renewal could not reach the source. Retry later.');}if(!response.ok)throw new Error('Authorization renewal failed. Reconnect this source.');const next=tokenPayload(await sourceJson(response),provider);await writeSecret(owner,provider,{...next,scope:next.scope??token.scope},guard);return next.access_token;}finally{await releaseRefreshLock(owner,`${provider}:refresh`,lock);}}

export interface WorkoutSnapshot{data:Workout;raw:unknown}
type WorkoutData=Workout&{sourceRecords?:Record<string,WorkoutSnapshot>;canonicalSourceData?:Workout;fieldSources?:Record<string,string>;raw?:unknown;linkedSourceRecords?:Record<string,unknown>};
const fields=['title','start','durationSec','distanceMeters','avgHr','calories','elevationMeters','sport','notes','laps','streams'] as const;
const rank=(ref:string)=>(({strava:0,tredict:1,fit:2,whoop:3} as Record<string,number>)[ref.split(':')[0]]??4);
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
/** Pure normalization: fresh source revisions update canonical fields while explicit local edits survive. */
export function reconcileWorkout(existing:Entry<Workout>|null,source:string,id:string,incoming:Workout,raw:unknown):WorkoutData{
 const previous=existing?.data as WorkoutData|undefined,ref=`${source}:${id}`,snapshots:Record<string,WorkoutSnapshot>={...previous?.sourceRecords};
 if(existing&&!Object.keys(snapshots).length)snapshots[`${existing.source}:${existing.sourceId}`]={data:existing.data,raw:previous?.raw??null};
 snapshots[ref]={data:incoming,raw};
 const ordered=Object.entries(snapshots).sort(([a],[b])=>rank(a)-rank(b)||a.localeCompare(b));
 const canonical={...incoming} as Workout;const fieldSources:Record<string,string>={};
 for(const field of fields){const chosen=ordered.find(([,snapshot])=>snapshot.data[field]!=null&&snapshot.data[field]!=='');if(chosen){Object.assign(canonical,{[field]:chosen[1].data[field]});fieldSources[field]=chosen[0];}}
 const result:WorkoutData={...previous,...canonical,sourceRefs:Object.keys(snapshots).sort(),sourceRecords:snapshots,canonicalSourceData:canonical,fieldSources};
 if(previous){const baseline=previous.canonicalSourceData??previous;for(const field of fields){if(!same(previous[field],baseline[field])){Object.assign(result,{[field]:previous[field]});fieldSources[field]='local';}}}
 return result;
}
export async function persistWorkout(owner:string,source:string,id:string,data:Workout,raw:unknown,zone:string,capturedGuard?:OperationGuard):Promise<{entry:Entry;duplicate:boolean;matched:boolean;updated:boolean}>{const guard=capturedGuard??await operationGuard(owner,source);let lock:string|null=null;for(let attempt=0;attempt<20&&!lock;attempt++){lock=await acquireRefreshLock(owner,'workout:merge');if(!lock)await new Promise(resolve=>setTimeout(resolve,100));}if(!lock)throw new Error('Another run import is active. Retry in a moment.');try{for(let attempt=0;attempt<3;attempt++){const entries=await listEntries(owner,true),ref=`${source}:${id}`;const sameSource=entries.find(e=>e.kind==='workout'&&((e.source===source&&e.sourceId===id)||!!(e.data as unknown as WorkoutData).sourceRecords?.[ref]));let existing=sameSource as unknown as Entry<Workout>|undefined;
 if(!existing){const candidates=ofKind<Workout>(entries,'workout').filter(e=>e.source!==source&&!Object.keys((e.data as WorkoutData).sourceRecords??{}).some(key=>key.startsWith(`${source}:`)));const matches=matchWorkout(data,candidates);if(matches.length>1)throw new Error('Ambiguous duplicate run. Review imported workouts before retrying.');existing=matches[0];}
 if(existing?.deleted)return{entry:existing as unknown as Entry,duplicate:true,matched:false,updated:false};
 const next=reconcileWorkout(existing??null,source,id,data,raw);try{const result=await saveEntry(owner,{id:existing?.id,kind:'workout',source:existing?.source??source,sourceId:existing?.sourceId??id,data:next,localDate:existing&&existing.data.start===next.start?existing.localDate:localDate(next.start,zone),expectedRevision:existing?.revision,guard});return{...result,updated:!!existing&&!result.duplicate,matched:!!existing&&!(existing.source===source&&existing.sourceId===id)};}catch(error){if((error as {staleOperation?:boolean}).staleOperation||(error as {status?:number}).status!==409||attempt===2)throw error;}}
 throw new Error('Run changed during import. Retry once the other import finishes.');}finally{await releaseRefreshLock(owner,'workout:merge',lock);}}

export async function syncSource(owner:string,source:string,capturedGuard?:OperationGuard){if(!PROVIDERS.includes(source as Provider))throw new Error('Unknown connection.');const guard=capturedGuard??await operationGuard(owner,source),entries=await listEntries(owner,true),zone=profileOf(entries).timezone,previous=entries.find(e=>e.id===`connection:${source}`);if(guard.disabled||previous?.data.disconnected===true)throw new Error('This source is disconnected. Enable it before syncing.');const lock=await acquireRefreshLock(owner,`${source}:sync`);if(!lock)throw new Error('This source is already syncing. Retry in a moment.');let count=0,complete=true;const dates:string[]=[];const since=new Date(Date.now()-90*86400000).toISOString();const until=new Date().toISOString();const deadline=Date.now()+45000;const coverageNote=source==='runna'?'Only events present in the current feed. Full-plan coverage and workout steps are unverified.':'Rolling 90-day window; older imported records retained. Completion describes this window only.';const missingFields=new Set<string>();try{
 if(source==='tredict'){const token=await credential(owner,'tredict');if(!token)throw new Error('Tredict needs a Personal API token with activityRead permission.');let url=`https://www.tredict.com/api/oauth/v2/activityList?extendedSummary=1&pageSize=50&endDate=${encodeURIComponent(since)}`;for(let page=0;url&&page<20;page++){const u=new URL(url);if(u.origin!=='https://www.tredict.com'||!u.pathname.startsWith('/api/oauth/v2/'))throw new Error('Unexpected Tredict pagination link.');const payload=record(await sourceJson(await fetchSource(url,token,deadline)));if(!Array.isArray(record(payload._embedded).activityList))throw new Error('Tredict returned an unsupported response. Sync is incomplete.');for(const raw of records(record(payload._embedded).activityList)){if(raw.sportType!=='running')continue;const s=record(raw.summary),start=new Date(String(raw.date)).toISOString();const data:Workout={title:String(raw.title??'Run'),start,durationSec:n(s.duration)??n(record(s.duration).active),distanceMeters:n(s.distance)??n(record(s.distance).total),avgHr:n(s.heartrate)??n(record(s.heartrate).avg),calories:n(s.calories),elevationMeters:n(record(s.altitude).ascent),sport:'running',notes:String(raw.notes??'')};if(data.distanceMeters==null)missingFields.add('distance');if(data.avgHr==null)missingFields.add('heart rate');await persistWorkout(owner,source,sourceId(raw.id??raw._id),data,raw,zone,guard);dates.push(localDate(start,zone));count++;if(Date.now()>deadline){complete=false;break;}}if(!complete)break;const next=record(record(payload._links).next).href;url=typeof next==='string'?new URL(next,'https://www.tredict.com').href:'';if(page===19&&url)complete=false;}missingFields.add('laps and streams (summary sync only)');}
 else if(source==='runna'){const feed=await credential(owner,'runna');if(!feed)throw new Error('Add a private Runna subscription URL, or import an ICS file.');const text=await(await fetchSource(validateRunnaUrl(feed),undefined,deadline)).text();if(text.length>1_500_000)throw new Error('Runna feed is too large. Import a smaller ICS file.');const preview=importCalendar(text,zone);for(const p of preview.candidates){if(p.kind!=='plan')continue;const id=await hash(p.key),existing=entries.find(e=>e.kind==='plan'&&e.source==='runna'&&(e.sourceId===p.key||e.sourceId===id));if(existing?.deleted)continue;const date=existing&&existing.data.start===p.data.start&&p.data.start?existing.localDate:p.date;await saveEntry(owner,{id:existing?.id,kind:'plan',source,sourceId:existing?.sourceId??p.key,localDate:date,data:{...p.data,completedWorkoutId:(existing?.data as unknown as Plan)?.completedWorkoutId??null,rawUid:p.key},expectedRevision:existing?.revision,guard});dates.push(date??p.date);count++;if(Date.now()>deadline){complete=false;break;}}complete=complete&&!preview.warnings.length;missingFields.add('structured intervals and pace targets');}
 else if(source==='strava'){const token=await providerToken(owner,'strava',guard);for(let page=1;page<=20;page++){const url=new URL('https://www.strava.com/api/v3/athlete/activities');url.searchParams.set('after',String(Math.floor(Date.parse(since)/1000)));url.searchParams.set('before',String(Math.ceil(Date.parse(until)/1000)));url.searchParams.set('page',String(page));url.searchParams.set('per_page','50');const payload:unknown=await sourceJson(await fetchSource(url.href,token,deadline));if(!Array.isArray(payload))throw new Error('Strava returned an unsupported response. Sync is incomplete.');for(const raw of records(payload)){if(!['Run','TrailRun','VirtualRun'].includes(String(raw.sport_type??raw.type)))continue;const start=new Date(String(raw.start_date)).toISOString(),data:Workout={title:String(raw.name??'Run'),start,durationSec:n(raw.moving_time),distanceMeters:n(raw.distance),avgHr:n(raw.average_heartrate),calories:null,elevationMeters:n(raw.total_elevation_gain),sport:'running',notes:''};if(data.distanceMeters==null)missingFields.add('distance');await persistWorkout(owner,source,sourceId(raw.id),data,raw,zone,guard);dates.push(localDate(start,zone));count++;if(Date.now()>deadline){complete=false;break;}}if(!complete||payload.length<50)break;if(page===20)complete=false;}missingFields.add('calories, laps, and streams (summary sync only)');}
 else if(source==='whoop'){const token=await providerToken(owner,'whoop',guard),all:Record<string,Raw[]>={};for(const resource of ['cycle','recovery','activity/sleep']){all[resource]=[];let next='';const seen=new Set<string>();for(let page=0;page<100;page++){const url=new URL(`https://api.prod.whoop.com/developer/v2/${resource}`);url.searchParams.set('start',since);url.searchParams.set('end',until);url.searchParams.set('limit','25');if(next)url.searchParams.set('nextToken',next);const payload=record(await sourceJson(await fetchSource(url.href,token,deadline)));if(!Array.isArray(payload.records))throw new Error('WHOOP returned an unsupported response. Sync is incomplete.');all[resource].push(...records(payload.records));next=typeof payload.next_token==='string'?payload.next_token:'';if(!next)break;if(seen.has(next))throw new Error('WHOOP repeated a pagination token. Retry later.');seen.add(next);if(page===99||Date.now()>deadline){complete=false;break;}}if(!complete)break;}if(!complete)throw new Error('WHOOP pagination did not finish within this sync. Existing records were preserved; retry later.');const pending:SaveInput[]=[];for(const cycle of all.cycle??[]){const recovery=all.recovery?.find(r=>r.cycle_id===cycle.id),sleep=all['activity/sleep']?.find(s=>s.cycle_id===cycle.id&&!s.nap),stage=record(record(sleep?.score).stage_summary),parts=[n(stage.total_light_sleep_time_milli),n(stage.total_slow_wave_sleep_time_milli),n(stage.total_rem_sleep_time_milli)];const existing=entries.find(e=>e.kind==='recovery'&&e.source===source&&e.sourceId===sourceId(cycle.id));if(existing?.deleted)continue;const date=existing&&existing.data.start===cycle.start?existing.localDate!:localDate(String(cycle.start),zone),score=record(cycle.score),recoveryScore=record(recovery?.score);if(cycle.score_state!=='SCORED')missingFields.add('unscored cycle expenditure');if(!recovery)missingFields.add('recovery');if(!sleep)missingFields.add('sleep');pending.push({id:existing?.id,expectedRevision:existing?.revision,guard,kind:'recovery',source,sourceId:sourceId(cycle.id),localDate:date,data:{start:cycle.start,end:cycle.end??null,scoreState:cycle.score_state,kilojoules:cycle.score_state==='SCORED'?n(score.kilojoule):null,strain:cycle.score_state==='SCORED'?n(score.strain):null,recovery:recovery?.score_state==='SCORED'?n(recoveryScore.recovery_score):null,hrv:recovery?.score_state==='SCORED'?n(recoveryScore.hrv_rmssd_milli):null,restingHr:recovery?.score_state==='SCORED'?n(recoveryScore.resting_heart_rate):null,sleepHours:sleep?.score_state==='SCORED'&&parts.every(p=>p!=null)?parts.reduce<number>((sum,p)=>sum+p!,0)/3600000:null,raw:{cycle,recovery:recovery??null,sleep:sleep??null}}});dates.push(date);count++;}await saveEntries(owner,pending);}
 dates.sort();const now=new Date().toISOString();await saveEntry(owner,{id:`connection:${source}`,kind:'connection',localDate:null,guard,data:{...previous?.data,provider:source,lastSuccess:now,lastAttempt:now,earliest:dates[0]??null,latest:dates.at(-1)??null,count,complete,error:null,disconnected:false,coverageNote,windowStart:source==='runna'?null:since,windowEnd:source==='runna'?null:until,missingFields:[...missingFields]}});return{source,count,complete};
 }catch(error){const message=error instanceof Error?error.message:'Sync failed. Retry later.';await saveEntry(owner,{id:`connection:${source}`,kind:'connection',localDate:null,guard,data:{...previous?.data,provider:source,lastAttempt:new Date().toISOString(),complete:false,error:message}});throw error;}finally{await releaseRefreshLock(owner,`${source}:sync`,lock);}}




