import {DEFAULT_PROFILE,addDays,type Entry,type Meal,type Workout} from './domain';
// Synthetic records only. These are never inserted into the user's database.
export function sampleEntries(date:string):Entry[]{const at=date+'T15:00:00Z',record=(id:string,kind:Entry['kind'],data:unknown,day:string|null=date):Entry=>({id:`sample-${id}`,kind,localDate:day,source:'fixture',sourceId:id,revision:1,updatedAt:at,data:data as Record<string,unknown>});const meal=(title:string,mealType:string,calories:number,carbs:number,protein:number,fat:number,fiber:number,etl:Meal['etl']):Meal=>({title,mealType,calories,carbs,protein,fat,fiber,mealTime:at,messageTime:at,notes:'Synthetic example. Not your food history.',confidence:'estimate',workoutId:null,...{etl}});return[
 record('profile','profile',{...DEFAULT_PROFILE,name:'Sample runner',weightKg:70,confirmed:true,raceDate:addDays(date,40),goalMinutes:240,diet:'Plant-forward; flexible around training',weightGoal:'Support marathon training',baselineIncludes:'Daily life; training adjustments added manually'}),
 record('breakfast','meal',meal('Oats, blueberries & soy yogurt','Breakfast',510,78,23,13,12,{fruitServings:1,soyG:150,nutsSeedsG:15})),record('lunch','meal',meal('Chickpea bowl with greens & brown rice','Lunch',680,92,24,24,18,{rawVegetablesG:180,cookedVegetablesG:160,beansG:160,starchCups:1})),record('snack','meal',meal('Banana & peanut butter toast','Snack',280,43,8,10,5,{fruitServings:1,nutsSeedsG:16})),
 record('run','workout',{title:'Easy miles',start:date+'T11:00:00Z',durationSec:3000,distanceMeters:8000,avgHr:138,calories:480,elevationMeters:35,sport:'running',notes:'Synthetic running example.'}),record('earlier','workout',{title:'Steady run',start:addDays(date,-1)+'T11:00:00Z',durationSec:3700,distanceMeters:10000,avgHr:145,calories:620,elevationMeters:45,sport:'running',notes:'Synthetic running example.'},addDays(date,-1)),
 record('long','plan',{title:'Long run · easy effort',start:addDays(date,1)+'T11:00:00Z',allDay:false,durationSec:7200,distanceMeters:20000,intensity:'Easy',notes:'Synthetic plan. Practice familiar fueling.',completedWorkoutId:null},addDays(date,1)),
 record('recovery','recovery',{start:date+'T09:00:00Z',end:addDays(date,1)+'T09:00:00Z',scoreState:'SCORED',kilojoules:11087.6,recovery:76,hrv:58,restingHr:49,sleepHours:7.7,strain:12.8}),record('day','day',{complete:false,adjustment:300,adjustmentReason:'Manual training-day adjustment',feedback:''})
 ]}
