import 'server-only';
import {createAdminClient} from './supabase/admin';
import type {Entry,Kind} from './domain';

type Row={id:string;kind:Kind;local_date:string|null;source:string;source_id:string;revision:number;updated_at:string;data:Record<string,unknown>;deleted:boolean};
const PAGE_SIZE=500;
const BUCKET='remy-files';
function ownerId(owner:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(owner))throw new Error('Invalid journal owner.');return owner;}
function storageError(error:{message?:string;code?:string}|null){if(!error)return;if(error.message?.includes('REMY_STALE_OPERATION'))throw Object.assign(new Error('The journal or connection changed while this request was running. Refresh before trying again.'),{status:409,staleOperation:true});if(error.message?.includes('REMY_CONFLICT'))throw Object.assign(new Error('This record changed in another session. Refresh before saving.'),{status:409});if(error.message?.includes('REMY_DELETING'))throw Object.assign(new Error('Journal deletion is in progress. Please retry later.'),{status:409});throw new Error('Journal storage request failed. Verify the Supabase migration and server configuration.');}
export function fromRow(row:Row):Entry{return{id:row.id,kind:row.kind,localDate:row.local_date,source:row.source,sourceId:row.source_id,revision:row.revision,updatedAt:row.updated_at,data:row.data,deleted:row.deleted};}
export async function listEntries(owner:string,includeDeleted=false):Promise<Entry[]>{const db=createAdminClient(),entries:Entry[]=[];for(let offset=0;;offset+=PAGE_SIZE){let query=db.from('remy_records').select('*').eq('owner',ownerId(owner)).order('id').range(offset,offset+PAGE_SIZE-1);if(!includeDeleted)query=query.eq('deleted',false);const {data,error}=await query;storageError(error);const rows=(data??[]) as Row[];entries.push(...rows.map(fromRow));if(rows.length<PAGE_SIZE)break;}return entries.sort((a,b)=>(b.localDate??'').localeCompare(a.localDate??'')||b.updatedAt.localeCompare(a.updatedAt));}
export async function getEntry(owner:string,id:string):Promise<Entry|null>{const {data,error}=await createAdminClient().from('remy_records').select('*').eq('owner',ownerId(owner)).eq('id',id).maybeSingle();storageError(error);return data?fromRow(data as Row):null;}
export interface OperationGuard{generation:number;provider?:string|null;version?:number|null;versions?:Record<string,number>;disabled?:boolean}
export async function operationGuard(owner:string,provider?:string):Promise<OperationGuard>{const {data,error}=await createAdminClient().rpc('remy_operation_state',{p_owner:ownerId(owner),p_provider:provider??null});storageError(error);if(!data||!Number.isSafeInteger(data.generation))throw new Error('Could not read journal state.');return data as OperationGuard;}
export interface SaveInput{guard?:OperationGuard;id?:string;kind:Kind;localDate:string|null;source?:string;sourceId?:string;data:unknown;expectedRevision?:number;deleted?:boolean}
export async function saveEntry(owner:string,input:SaveInput):Promise<{entry:Entry;duplicate:boolean}>{const id=input.id??crypto.randomUUID();const {data,error}=await createAdminClient().rpc('remy_save_entry',{p_owner:ownerId(owner),p_id:id,p_kind:input.kind,p_local_date:input.localDate,p_source:input.source??null,p_source_id:input.sourceId??null,p_data:input.data,p_expected_revision:input.expectedRevision??null,p_deleted:!!input.deleted,p_guard:input.guard??null});storageError(error);if(!data?.entry)throw new Error('Could not save record.');return{entry:fromRow(data.entry as Row),duplicate:!!data.duplicate};}
export async function saveEntries(owner:string,inputs:SaveInput[]):Promise<void>{for(let offset=0;offset<inputs.length;offset+=200){const batch=inputs.slice(offset,offset+200).map(input=>({...input,id:input.id??crypto.randomUUID()}));const {error}=await createAdminClient().rpc('remy_save_entries',{p_owner:ownerId(owner),p_entries:batch});storageError(error);}}
export async function undo(owner:string,id:string,expectedRevision:number,guard?:OperationGuard):Promise<{entry:Entry;duplicate:boolean}>{if(!Number.isInteger(expectedRevision)||expectedRevision<1)throw new Error('A valid revision is required.');const {data,error}=await createAdminClient().rpc('remy_undo_entry',{p_owner:ownerId(owner),p_id:id,p_expected_revision:expectedRevision,p_guard:guard??null});storageError(error);if(!data?.entry)throw new Error('Could not undo record.');return{entry:fromRow(data.entry as Row),duplicate:!!data.duplicate};}
export async function hash(text:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(bytes)].map(n=>n.toString(16).padStart(2,'0')).join('');}

async function journalState(owner:string){const {data,error}=await createAdminClient().rpc('remy_journal_state',{p_owner:ownerId(owner)});storageError(error);return data as {generation:number;deleting:boolean};}
export async function uploadOriginal(owner:string,path:string,text:string,guard?:OperationGuard){ownerId(owner);if(!path||path.startsWith('/')||path.split('/').some(p=>!p||p==='.'||p==='..')||!/^[a-zA-Z0-9/_-]+$/.test(path))throw new Error('Invalid import storage path.');if(new TextEncoder().encode(text).byteLength>10_000_000)throw new Error('Original import exceeds the 10 MB storage limit.');const before=await journalState(owner);if(guard&&guard.generation!==before.generation)throw Object.assign(new Error('The journal changed during this import. Refresh before trying again.'),{status:409});if(before.deleting)throw new Error('Journal deletion is in progress.');const objectPath=`${owner}/${before.generation}/${path}`,db=createAdminClient();const {error}=await db.storage.from(BUCKET).upload(objectPath,text,{contentType:'text/plain',upsert:true});storageError(error);const after=await journalState(owner);if(after.deleting||after.generation!==before.generation){await db.storage.from(BUCKET).remove([objectPath]);throw new Error('The journal changed during upload. Please retry.');}return{path:objectPath,bucket:BUCKET};}
async function objectPaths(owner:string){const bucket=createAdminClient().storage.from(BUCKET),paths:string[]=[];async function walk(prefix:string){for(let offset=0;;offset+=PAGE_SIZE){const {data,error}=await bucket.list(prefix,{limit:PAGE_SIZE,offset,sortBy:{column:'name',order:'asc'}});storageError(error);for(const item of data??[]){const full=`${prefix}/${item.name}`;if(item.id)paths.push(full);else await walk(full);}if((data?.length??0)<PAGE_SIZE)break;}}await walk(ownerId(owner));return paths;}
export async function exportJournal(owner:string){const entries=await listEntries(owner,true),revisions:unknown[]=[];for(let offset=0;;offset+=PAGE_SIZE){const {data,error}=await createAdminClient().from('remy_revisions').select('record_id,revision,snapshot,created_at').eq('owner',ownerId(owner)).order('record_id').order('revision').range(offset,offset+PAGE_SIZE-1);storageError(error);revisions.push(...data??[]);if((data?.length??0)<PAGE_SIZE)break;}const files=await objectPaths(owner);return{version:1,exportedAt:new Date().toISOString(),entries,revisions,files,filesNote:'Original files remain private; this export lists their paths. Credentials are never exported.'};}
export async function deleteJournal(owner:string){const db=createAdminClient();const begin=await db.rpc('remy_begin_delete',{p_owner:ownerId(owner)});storageError(begin.error);const paths=await objectPaths(owner);for(let i=0;i<paths.length;i+=100){const {error}=await db.storage.from(BUCKET).remove(paths.slice(i,i+100));storageError(error);}const {error}=await db.rpc('remy_finish_delete',{p_owner:owner});storageError(error);return{deleted:true,filesDeleted:paths.length};}

async function cipherKey(){const secret=process.env.SECRET_ENCRYPTION_KEY;if(!secret||secret.length<32)throw new Error('Secure connection storage is not configured. Set SECRET_ENCRYPTION_KEY on the server.');return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)),'AES-GCM',false,['encrypt','decrypt']);}
export async function writeSecret(owner:string,provider:string,value:unknown,guard?:OperationGuard){const iv=crypto.getRandomValues(new Uint8Array(12)),aad=new TextEncoder().encode(`${owner}:${provider}`);const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad},await cipherKey(),new TextEncoder().encode(JSON.stringify(value)));const encoded=`v1.${Buffer.from(iv).toString('base64')}.${Buffer.from(ciphertext).toString('base64')}`;const {error}=await createAdminClient().rpc('remy_write_secret',{p_owner:ownerId(owner),p_provider:provider,p_ciphertext:encoded,p_guard:guard??null});storageError(error);}
export async function readSecret<T>(owner:string,provider:string):Promise<T|null>{const {data,error}=await createAdminClient().from('remy_secrets').select('ciphertext').eq('owner',ownerId(owner)).eq('provider',provider).maybeSingle();storageError(error);if(!data)return null;try{const [v,a,b]=data.ciphertext.split('.');if(v!=='v1'||!a||!b)throw new Error();const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(a,'base64'),additionalData:new TextEncoder().encode(`${owner}:${provider}`)},await cipherKey(),Buffer.from(b,'base64'));return JSON.parse(new TextDecoder().decode(plain)) as T;}catch{throw new Error('Saved credentials cannot be unlocked. Reconnect this source with the current server encryption key.');}}
export async function deleteSecret(owner:string,provider:string,guard?:OperationGuard){const {error}=await createAdminClient().rpc('remy_delete_secret',{p_owner:ownerId(owner),p_provider:provider,p_guard:guard??null});storageError(error);}
export async function enableSource(owner:string,provider:string,guard:OperationGuard){const {error}=await createAdminClient().rpc('remy_enable_source',{p_owner:ownerId(owner),p_provider:provider,p_guard:guard});storageError(error);}
export async function disconnectSource(owner:string,provider:string,guard?:OperationGuard){const {error}=await createAdminClient().rpc('remy_disconnect_source',{p_owner:ownerId(owner),p_provider:provider,p_guard:guard??null});storageError(error);}
export async function acquireRefreshLock(owner:string,provider:string){const token=crypto.randomUUID();const {data,error}=await createAdminClient().rpc('remy_acquire_lock',{p_owner:ownerId(owner),p_provider:provider,p_token:token,p_seconds:120});storageError(error);return data?token:null;}
export async function releaseRefreshLock(owner:string,provider:string,token:string){const {error}=await createAdminClient().rpc('remy_release_lock',{p_owner:ownerId(owner),p_provider:provider,p_token:token});storageError(error);}
