import {z} from 'zod';
const optionalNumber=(max:number)=>z.number().finite().min(0).max(max).nullable();
export const dateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(s=>{const d=new Date(s+'T12:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===s},'Use a valid calendar date');
export const etlSchema=z.object({rawVegetablesG:optionalNumber(10000).optional(),cookedVegetablesG:optionalNumber(10000).optional(),beansG:optionalNumber(10000).optional(),soyG:optionalNumber(10000).optional(),fruitServings:optionalNumber(100).optional(),starchCups:optionalNumber(100).optional(),nutsSeedsG:optionalNumber(2000).optional(),flaxG:optionalNumber(500).optional(),avocadoG:optionalNumber(3000).optional(),driedFruitG:optionalNumber(3000).optional(),flexCalories:optionalNumber(15000).optional(),runFuelCalories:optionalNumber(15000).optional()}).strict();
export const mealSchema=z.object({title:z.string().trim().min(1).max(300),mealType:z.enum(['Breakfast','Lunch','Dinner','Snack','Run fuel']),mealTime:z.string().datetime({offset:true}).nullable(),messageTime:z.string().datetime({offset:true}).nullable(),notes:z.string().max(2000),confidence:z.enum(['label','recipe','estimate','unknown']),workoutId:z.string().max(120).nullable(),calories:optionalNumber(15000),carbs:optionalNumber(3000),protein:optionalNumber(1000),fat:optionalNumber(1000),fiber:optionalNumber(300),photoId:z.string().max(200).nullable().optional(),etl:etlSchema.optional()}).strict();
const band=z.tuple([z.number().min(1).max(15),z.number().min(1).max(15)]).refine(a=>a[0]<=a[1]);
export const profileSchema=z.object({name:z.string().max(100),timezone:z.string().refine(s=>{try{new Intl.DateTimeFormat('en',{timeZone:s});return true}catch{return false}}),baseline:z.number().min(500).max(10000),baselineIncludes:z.string().max(1000),weightKg:z.number().min(25).max(350).nullable(),raceDate:dateSchema.nullable(),goalMinutes:z.number().min(90).max(1000).nullable(),diet:z.string().max(2000),weightGoal:z.string().max(1000),confirmed:z.boolean(),gutTolerance:z.string().max(1000),carbBands:z.object({light:band,moderate:band,high:band})}).strict();
export const daySchema=z.object({complete:z.boolean(),adjustment:z.number().min(-2000).max(10000),adjustmentReason:z.string().max(500),feedback:z.string().max(2000),weightKg:z.number().min(25).max(350).nullable().optional()}).refine(d=>!d.adjustment||!!d.adjustmentReason.trim(),'Add a reason for the calorie adjustment');
export const workoutSchema=z.object({title:z.string().min(1).max(300),start:z.string().datetime({offset:true}),durationSec:optionalNumber(604800),distanceMeters:optionalNumber(1000000),avgHr:optionalNumber(250),calories:optionalNumber(20000),elevationMeters:optionalNumber(30000),sport:z.string().max(50),notes:z.string().max(2000),sourceRefs:z.array(z.string()).optional(),laps:z.array(z.unknown()).max(5000).optional(),streams:z.unknown().optional(),perceivedEffort:optionalNumber(10).optional(),soreness:optionalNumber(10).optional()});
export const planSchema=z.object({title:z.string().min(1).max(300),start:z.string().datetime({offset:true}).nullable(),allDay:z.boolean(),durationSec:optionalNumber(604800),distanceMeters:optionalNumber(1000000),intensity:z.string().max(200),notes:z.string().max(4000),completedWorkoutId:z.string().nullable(),originalDate:dateSchema.optional(),cancelled:z.boolean().optional()});
const candidateBase={key:z.string().min(1).max(4000),date:dateSchema,warning:z.string().max(2000).optional()};
export const importCandidateSchema=z.discriminatedUnion('kind',[
 z.object({...candidateBase,kind:z.literal('meal'),data:mealSchema}).strict(),
 z.object({...candidateBase,kind:z.literal('workout'),data:workoutSchema}).strict(),
 z.object({...candidateBase,kind:z.literal('plan'),data:planSchema}).strict()
]);
export const importCommitSchema=z.object({action:z.literal('commit'),reviewed:z.literal(true),source:z.enum(['remy-etl','strava','runna','fit']),original:z.string().max(1_500_000).optional(),candidates:z.array(importCandidateSchema).min(1).max(1000)}).strict().superRefine((value,ctx)=>{const expected=value.source==='remy-etl'?'meal':value.source==='runna'?'plan':'workout';value.candidates.forEach((item,index)=>{if(item.kind!==expected)ctx.addIssue({code:z.ZodIssueCode.custom,path:['candidates',index,'kind'],message:`${value.source} imports must contain ${expected} records.`})})});
